ALTER TABLE users ADD COLUMN email_confirmation_token CHARACTER VARYING(255) NULL;
ALTER TABLE users ADD COLUMN email_confirmation_sent_at TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE users ADD COLUMN email_confirmed_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
